api_token: null
repositories:
  - matomo-org/matomo
  - matomo-org/tag-manager
  - matomo-org/matomo-log-analytics
  - matomo-org/matomo-php-tracker
  - matomo-org/referrer-spam-blacklist
  - matomo-org/tracker-proxy
  - matomo-org/device-detector
  - matomo-org/searchengine-and-social-list
  - matomo-org/component-network
  - matomo-org/component-ini
  - matomo-org/component-decompress
  - matomo-org/component-cache
  - matomo-org/matomo-package
  - matomo-org/matomo-icons
labels_to_ignore:
  - wontfix
  - not-in-changelog
  - invalid
  - duplicate
  - answered
  - worksforme
sort_by_labels:
  - Critical
  - Major
  - 'c: New plugin'
  - 'c: Security'
  - Enhancement
  - 'c: Performance'
  - Regression
  - 'c: Design / UI'
  - 'c: Usability'
  - 'c: Accessibility'
  - Task
  - 'c: Platform'
  - Bug
  - 'c: Website matomo.org'
  - 'c: i18n'
  - RFC

is_matomo: True